-- MySQL Script generated by MySQL Workbench
-- Sat Oct 23 13:17:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema galaxy-store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema galaxy-store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `galaxy-store` DEFAULT CHARACTER SET utf8 ;
USE `galaxy-store` ;

-- -----------------------------------------------------
-- Table `galaxy-store`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galaxy-store`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `mobileNumber` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galaxy-store`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galaxy-store`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galaxy-store`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galaxy-store`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cust_fk_idx` (`customer_id` ASC) VISIBLE,
  INDEX `prod_fk_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `cust_fk`
    FOREIGN KEY (`customer_id`)
    REFERENCES `galaxy-store`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prod_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `galaxy-store`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
